#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Feb 08 16:04:05 COT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=BSL_v10.1.zip
